DROP DATABASE IF EXISTS db_todolist;
CREATE DATABASE db_todolist;
USE db_todolist;

DROP TABLE IF EXISTS user;
CREATE TABLE user(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT(NOW()),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

DROP TABLE IF EXISTS task;
CREATE TABLE task(
    id INT NOT NULL AUTO_INCREMENT,
    iduser INT NOT NULL,
    title VARCHAR(30) NOT NULL UNIQUE,
    content VARCHAR(50) NOT NULL,
    state ENUM('IP','F') DEFAULT 'IP',
    create_at TIMESTAMP NOT NULL DEFAULT(NOW()),
    PRIMARY KEY(id),
    FOREIGN KEY (iduser) REFERENCES user(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

